{% set version = "0.3.0" %}
{% set gh_org = "danielballan" %}
{% set gh_repo = "nbexamples" %}

package:
  name: {{ gh_repo }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-v{{ version }}.tar.gz
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/v{{ version }}.tar.gz
  sha256: 80e7217d27583c24dffdd8011d60792bc5a797cec9fe9e9a8b4e9f0709f0ffd1

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - notebook >=4.2.0
    - python
    - setuptools
  run:
    - nbconvert
    - nbformat
    - notebook >=4.2.0
    - python

test:
  imports:
    - nbexamples

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3-Clause
  summary: Jupyter Notebook extension that shows a list of example notebooks for users to preview and clone

extra:
  recipe-maintainers:
    - danielballan
    - ericdill
    - mariusvniekerk
    - parente
