# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lOJJT7J7oBpC6fLtElzyvq8Uw+06xoBPHGXQRpc4u1F1l0gjrtkWM+8MJTA5jRkdgQ6R3CIyxR2yx6m5nF13Jgp5pyomYzQyiZZyY9xdfHzPVFAwUp4GulJFCUUj4uba1hTvbSBnLgdJmp0yzl4HpDWZlcYVkQV+knoXsUFR9tbwU75UCryzkJkIjR8w7mvoZ4y+VRTF5JfHyPmmq0f34oaZPMtqQpA1PCzK0Ncc4xzNsYVVbEwqkz2YXgrscEGqIogC3KqeMfNRpT8iHIN0jaWxgoRMZofQuw34jfeufc7uo2rX05scmnVerrtVeH5qRh/dRW6nC338kjppQrIeWar/lUBqQBExZVD7gI0FHGDmbthPEml8EQS/OnLWfU2pFf5LysLBteTcCz0nZLNcSOfQ8bRrGOK6gv9PfCEp2093v+irFFOmtLsoos5f4hL2kGj+rnwSCjf40c0B4I1lb/o5GviruuK2m8cuBSyL1vEsdYbvH6y4i14oubqfRYzRQxLYmUfE8Dsg/OgpvYeddxe3ITBpPj+rAajTfpFjD0X1dabDnZvLId/+418XXxn6SNXzyfIXuGkBWgWSnF6unoctp0WSD0ti9IRCJf+kYg5hMgtR7tHGQFQwIDlESYeuxILgn1xW31JH2jnTBVQ3jkeGCAFhAX5SMc5Ri8BI100="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
