travis:
  secure:
    BINSTAR_TOKEN: gg+xibRxlSPMydB1zKg3wlh/4abG/HBBdQ3hRaVIrz04YQhVNUhRVYRaTZVmBLtHFn7jaI6Em/BTQfOhFKdwocr2BR0djiC8wzHlroc38MRR/P610Zbw7NHG2EPePkQvVAYzFdjsT3jSV5dZL2gzXg3PiT2NOsITAvjnrDzTXf60mnv+R1PYSZthxSU48N+7hiuePcMa195NV+9oQDIsxmMvoL+5FwWEhtvMJTpOiCQ6suad/Q5BAzQc1DSA90iD3E9LdBPqZ6mOMqVWWptJxf9D4lfy7c5uN/qokGcfPEVTcDI64HwY7ShDH2HZ+HXOy/2ZbQzItLRTofBJPMPfbvFVMG0OqquWywJwrnft6xJVxPPGDRIrCXsY3I955WClLXo0P2T9H+Ox2YpbelysAaMSPBy6Di6e346jgxiE+/7X85k/JfUgm1XW0fkkerWKXnMYXoc2egHK5ZjkHL2OgU12PXaBwoh96OiQinsRVzjnfWwT44Zu8cJ79l38xocd+1q/nDX9QJO223DkzvcbnGVMwAEAQXckiSIQBV1uP9/2YDJgsnMRmA46YWTEoFQQ79m8t+cT+4EJL3tQPLLPpXQX3MpMRN31Ka7RJ/hXs/5eA6a3AXWMRKw10YF9D03nTXlK3S9E4m3UFzc9oY/TnN8Wmo0xTeq38a0JjOl6gpo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
