travis:
  secure:
    BINSTAR_TOKEN: lOJJT7J7oBpC6fLtElzyvq8Uw+06xoBPHGXQRpc4u1F1l0gjrtkWM+8MJTA5jRkdgQ6R3CIyxR2yx6m5nF13Jgp5pyomYzQyiZZyY9xdfHzPVFAwUp4GulJFCUUj4uba1hTvbSBnLgdJmp0yzl4HpDWZlcYVkQV+knoXsUFR9tbwU75UCryzkJkIjR8w7mvoZ4y+VRTF5JfHyPmmq0f34oaZPMtqQpA1PCzK0Ncc4xzNsYVVbEwqkz2YXgrscEGqIogC3KqeMfNRpT8iHIN0jaWxgoRMZofQuw34jfeufc7uo2rX05scmnVerrtVeH5qRh/dRW6nC338kjppQrIeWar/lUBqQBExZVD7gI0FHGDmbthPEml8EQS/OnLWfU2pFf5LysLBteTcCz0nZLNcSOfQ8bRrGOK6gv9PfCEp2093v+irFFOmtLsoos5f4hL2kGj+rnwSCjf40c0B4I1lb/o5GviruuK2m8cuBSyL1vEsdYbvH6y4i14oubqfRYzRQxLYmUfE8Dsg/OgpvYeddxe3ITBpPj+rAajTfpFjD0X1dabDnZvLId/+418XXxn6SNXzyfIXuGkBWgWSnF6unoctp0WSD0ti9IRCJf+kYg5hMgtR7tHGQFQwIDlESYeuxILgn1xW31JH2jnTBVQ3jkeGCAFhAX5SMc5Ri8BI100=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
